# hydra.job.chdir: false

headless: false

sim: ${task.sim}
env: ${task.env}

total_frames: 250_000_000
max_iters: -1
eval_interval: -1
save_interval: 1000
seed: 0

viewer:
  resolution: [960, 720]
  eye: [16, 0., 12.]
  lookat: [0., 0., 1.]

wandb:
  group: ${oc.select:..task.name}
  run_name: ${oc.select:..task.name,test}-${oc.select:..algo.name,none}
  job_type: train
  entity: mlic_academic2
  project: drone
  mode: online # set to 'disabled' when debugging locally
  run_id: 
  monitor_gym: true
  tags: 

defaults:
  - task: Logistics
  - algo: mappo
  - _self_
